insert into regioni (nome) values ("Valle d\'Aosta");
insert into regioni (nome) values ('Piemonte');
insert into regioni (nome) values ('Liguria');
insert into regioni (nome) values ('Lombardia');
insert into regioni (nome) values ('Trentino-Alto Adige');
insert into regioni (nome) values ('Veneto');
insert into regioni (nome) values ('Friuli-Venezia Giulia');
insert into regioni (nome) values ('Emilia-Romagna');
insert into regioni (nome) values ('Toscana');
insert into regioni (nome) values ('Marche');
insert into regioni (nome) values ('Umbria');
insert into regioni (nome) values ('Lazio');
insert into regioni (nome) values ('Abruzzo');
insert into regioni (nome) values ('Molise');
insert into regioni (nome) values ('Campania');
insert into regioni (nome) values ('Basilicata');
insert into regioni (nome) values ('Puglia');
insert into regioni (nome) values ('Calabria');
insert into regioni (nome) values ('Sicilia');
insert into regioni (nome) values ('Sardegna');